### ISSUE TITLE
CSS how to load css when using @noview in a plugin

### ISSUE THREAD

**Issue by vegarringdal** [aurelia/skeleton-plugin#26] opened 2016-03-25 13:59 UTC
Tried using global resources in a aurelia grid plugin Im making to load the plugins css.
Tried this in my grid plugin `config.globalResources('./v-grid', './styles/v-grid.css');` 
But then it says it cant find v-grid.css.js
Im using noView, so I cant really do require to get it in.
Tried to look in the docs, but didnt see anything

Here is the grid Im making a plugin from:
https://github.com/vegarringdal/vGrid

**Comment by EisenbergEffect** [comment] 2016-03-25 14:05
This is a regression in the latest release. We are working on fixing it now. We've got an issue open for it. Closing this as a duplicate.

**Closed as completed by EisenbergEffect** 2016-03-25 14:05 UTC
Labels: duplicate

**Comment by vegarringdal** [comment] 2016-03-25 14:14
@EisenbergEffect Could you add a link to the issue so I can subscribe to it, so I know when its fixed and I can give plugins a new try :-)

**Comment by EisenbergEffect** [comment] 2016-03-25 14:20
https://github.com/aurelia/loader-default/issues/33

**Comment by vegarringdal** [comment] 2016-03-25 15:17
Adding !text makes the error messages go away and I can see the css file loads, but it does not work like I expected it , because the classes in css file isnt accessable.

`config.globalResources('./v-grid', './styles/v-grid.css!text');`

A little bit unsure if this is just the same issue, or more, so Ill add it here.
Could be just me miss understanding how to add css files to plugins

**Comment by EisenbergEffect** [comment] 2016-03-25 15:18
As I mentioned, this is a regression. It's being worked on right now.

**Comment by Thanood** [comment] 2016-03-26 09:13
@vegarringdal Try to just import your css in `index.js` - afaik it should be added to the `<head>`, like this:

``` javascript
import './styles/v-grid-css!';
export function configure(config) {
  config.globalResources('./v-grid');
}
```

Since you're building a plugin: this is dependent on SystemJS loaders. It won't be compatible with the webpack-loader. So this should be considered a workaround.

Is that

``` javascript
config.globalResources('./v-grid', './styles/v-grid.css');
```

actually the right way to load css as a global resource if you deliver a custom attribute or a `@noview` component? I've been struggling with direct imports a little, trying to get these compatible with webpack. That would be a great thing. :smile:

**Comment by vegarringdal** [comment] 2016-03-26 10:05
@Thanood 
tried, get  

```
system.src.js:4597 GET http://127.0.0.1:9000/dist/css.js 404 (Not Found)I @ system.src.js:4597(anonymous function) @ system.src.js:4597(anonymous function) @ system.src.js:4597(anonymous function) @ system.src.js:4597(anonymous function) @ system.src.js:4597(anonymous function) @ system.src.js:4597(anonymous function) @ system.src.js:4597(anonymous function) @ system.src.js:4597(anonymous function) @ system.src.js:4597(anonymous function) @ system.src.js:4597
system.js:4 Uncaught (in promise) Error: XHR error (404 Not Found) loading http://127.0.0.1:9000/dist/css.js(…)
```

What I did: 
-added import statement here: https://github.com/vegarringdal/test/blob/master/src/index.js
-ran gulp build
-uploaded it here to my dummy test playground: https://github.com/vegarringdal/test
-importet it to my project: jspm install vgrid=github:vegarringdal/test
- then added plugin to main.js:

```
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .globalResources()
    .plugin("vgrid")

  aurelia.start().then(a => a.setRoot());
}
```

If you see something Im doing wrong, or have other suggestions then please tell me :-)

**Comment by Thanood** [comment] 2016-03-26 10:06
Did you do `jspm install css`?
It seems to be missing the css loader.

**Comment by vegarringdal** [comment] 2016-03-26 11:14
@Thanood 
No I didnt, didnt know I needed that, looks to be working now.
But I hope we will be able to do the same with globalResource when bug is fixed.
But now I can atleast try it as a plugin and see how version etc works, jspm etc is so new to me

**Comment by vegarringdal** [comment] 2016-03-26 13:06
@Thanood 
Info:
The file from ahmedshuhel made it possible for me to load css when just tested in main.js add added css& js file, gave error before I replaced the framework.js file.
